# Entrega 1 Optimizacion

### Grupo 4

Integrantes:
* Carlos Arevalo
* Nangel Coello
* Daniel Maturana 
* Benjamin Pavez

## Problema de Asignación

### Enunciado
En una empresa se busca asignar de forma óptima a sus trabajadores en las diversas tareas que deben llevarse a cabo. Se sabe que los trabajadores están clasificados según su nivel de especialización. Además, las tareas están clasificadas según los mismos niveles de especialización de tal manera que una tarea de cierto nivel de especialización puede ser ejecutada solo por trabajadores de tal nivel, o bien, uno superior, pero no inferior.

Cada tarea requiere de cierta cantidad de tiempo para ser completada y cada trabajador puede ser asignado por una cantidad determinada de tiempo. Todas las tareas deben ser completadas en su totalidad.

Todos los trabajadores de cierto nivel de especialización suponen un costo por unidad de tiempo y un costo fijo asociado a asignar a cierto trabajador a cierta tarea en específico. A estos costos los llamaremos costos 1. Además, existe un costo por sobrecalificación asociada a cada tarea.

Cada trabajador puede ser asignado a máximo \$N\$ tareas, pero para completar una tarea puede requerirse más de un trabajador. No obstante, no se pueden asignar más de dos tercios del total de los trabajadores a solo una tarea.

La empresa cuenta con un presupuesto \$P\$ para la asignación de tareas que no puede ser superado, y busca:
1. Minimizar \$costos\$ \$1\$.
2. Minimizar costos de sobrecalificación.

### Formulación del Modelo Matemático

#### Conjuntos:
- *I* : Conjunto de trabajadores, i $\in$ *I*.
- *J* : Conjunto de tareas, j $\in$ *J*.
- *L* : Conjunto de niveles de especialización,  l $\in$ \{1, 2, 3, $\ldots$, 8\}.

#### Parámetros:
- \$ E_i \$: Nivel de especialización del trabajador \$ i \$.
- \$ S_j \$: Nivel de especialización requerido para la tarea \$ j \$.
- \$ T_j \$: Tiempo requerido para completar la tarea \$ j \$.
- \$ H_i \$: Tiempo disponible del trabajador \$ i \$.
- \$ C_{ij} \$: Costo fijo asociado a asignar al trabajador \$ i \$ a la tarea \$ j \$.
-\$ U_i \$: Costo por unidad de tiempo del trabajador \$ i \$.
- \$ O_{ij} \$: Costo por sobrecalificación de asignar al trabajador \$ i \$ a la tarea \$ j \$ (si \$ E_i > S_j \$).
- \$ P \$: Presupuesto disponible.
- \$ N \$: Máximo número de tareas a las que puede ser asignado un trabajador.

#### Variables:
- \$x_{ij}\$ : Variable binaria que indica si el trabajador \$i\$ es asignado a la tarea \$j\$.
- \$y_{ij}\$ : Tiempo que el trabajador \$i\$ dedica a la tarea \$j\$.

#### Función objetivo:
Minimizar los costos totales (costos 1 y costos de sobrecalificación):

\$ 
\text{Minimizar} \quad Z = \sum_{i \in I} \sum_{j \in J} (C_{ij} \cdot x_{ij} + U_i \cdot y_{ij} + O_{ij} \cdot x_{ij})
\$

#### Restricciones:
1. **Asignación completa de tareas**: Cada tarea debe ser completada en su totalidad.
   \$
   \sum_{i \in I} y_{ij} = T_j \quad \forall j \in J
   \$

2. **Tiempo disponible por trabajador**: Un trabajador no puede ser asignado más allá de su tiempo disponible.
   \$
   \sum_{j \in J} y_{ij} \leq H_i \quad \forall i \in I
   \$

3. **Nivel de especialización**: Un trabajador puede ser asignado a una tarea solo si su nivel de especialización es igual o superior al requerido.
   \$
   x_{ij} = 0 \quad \text{si} \quad E_i < S_j
   \$

4. **Relación entre \$x_{ij}\$ y \$y_{ij}\$** : Si un trabajador \$i\$ no está asignado a una tarea \$j\$, el tiempo dedicado es cero.
   \$
   y_{ij} \leq T_j \cdot x_{ij} \quad \forall i \in I, \forall j \in J
   \$

5. **Límite de tareas por trabajador**: Un trabajador puede ser asignado a un máximo de \$N\$ tareas.
   \$
   \sum_{j \in J} x_{ij} \leq N \quad \forall i \in I
   \$

6. **Presupuesto**: El costo total no debe superar el presupuesto disponible.
   \$
   \sum_{i \in I} \sum_{j \in J} (C_{ij} \cdot x_{ij} + U_i \cdot y_{ij} + O_{ij} \cdot x_{ij}) \leq P
   \$

7. **Límite de asignación por tarea**: No se pueden asignar más de dos tercios de los trabajadores a una sola tarea.
   \$
   \sum_{i \in I} x_{ij} \leq \frac{2}{3}|I| \quad \forall j \in J
   \$

8. **Variables binarias**:
   \$
   x_{ij} \in \{0, 1\} \quad \forall i \in I, \forall j \in J
   \$

### Posibles Casos de Infactibilidad

- **Insuficiente tiempo disponible**: Si el tiempo total requerido por todas las tareas es mayor que la suma del tiempo disponible de todos los trabajadores.
- **Presupuesto insuficiente**: Si el presupuesto disponible es menor que el costo mínimo necesario para asignar todas las tareas.
- **Desajuste en niveles de especialización**: Si hay tareas para las cuales no hay trabajadores con un nivel de especialización adecuado.
- **Exceso de tareas por trabajador**: Si las restricciones de un máximo de \$N\$ tareas por trabajador no pueden cumplirse debido a la cantidad de tareas y trabajadores.
- **Límite de asignación por tarea**: Si algunas tareas requieren más trabajadores de los que pueden ser asignados sin exceder el límite de dos tercios.


### Generador de Instancias en Python

In [8]:
import numpy as np
import random

def generar_instancia(I, J, N):
    # Niveles de especialización (distribución triangular)
    E = np.random.triangular(1, 8, 8, I).astype(int)
    S = np.random.triangular(1, 1, 8, J).astype(int)
    
    # Tiempo disponible por trabajador y tiempo requerido por tarea
    if N == 1:
        H = np.random.randint(300, 451, I)
        T = np.random.randint(30, 301, J)
    elif N == 2:
        H = np.random.randint(400, 551, I)
        T = np.random.randint(30, 401, J)
    elif N == 3:
        H = np.random.randint(500, 651, I)
        T = np.random.randint(30, 501, J)
    elif N == 4:
        H = np.random.randint(600, 751, I)
        T = np.random.randint(30, 601, J)
    
    # Costos por unidad de tiempo por trabajador
    U = [random.randint(5 + 5 * (e - 1), 10 + 5 * (e - 1)) for e in E]
    
    # Costos fijos y costos de sobrecalificación
    C = np.random.randint(4000, 8001, (I, J))
    O = np.random.randint(10000, 30001, (I, J))
    
    # Presupuesto
    P = random.randint(2 * (I // 3) * 10000, 4 * (I // 5) * 10000)
    
    return E, S, H, T, U, C, O, P

# Ejemplo de generación de instancia
I, J, N = 10, 5, 4
E, S, H, T, U, C, O, P = generar_instancia(I, J, N)
print("Niveles de especialización de trabajadores:", E)
print("Niveles de especialización requeridos por tareas:", S)
print("Tiempos disponibles de trabajadores:", H)
print("Tiempos requeridos por tareas:", T)
print("Costos por unidad de tiempo de trabajadores:", U)
print("Costos fijos de asignación:", C)
print("Costos de sobrecalificación:", O)
print("Presupuesto:", P)


Niveles de especialización de trabajadores: [2 5 6 6 5 4 4 4 6 4]
Niveles de especialización requeridos por tareas: [1 3 5 4 2]
Tiempos disponibles de trabajadores: [714 626 690 712 614 600 678 714 685 675]
Tiempos requeridos por tareas: [236 335 466 572 462]
Costos por unidad de tiempo de trabajadores: [14, 27, 31, 30, 29, 20, 20, 23, 31, 22]
Costos fijos de asignación: [[5227 4998 5126 4414 6682]
 [4731 5358 7750 5429 4678]
 [5454 6102 5590 4165 5472]
 [7831 4757 7775 4647 5063]
 [5411 5950 7888 4992 5426]
 [6199 4721 7244 4531 7150]
 [5773 4688 7514 5366 4651]
 [6039 6314 6779 4421 5444]
 [4766 7809 6121 4036 6671]
 [6619 4723 6863 5297 6454]]
Costos de sobrecalificación: [[21828 16559 26148 27986 10110]
 [27083 20232 22400 25830 19375]
 [28016 27057 15582 29087 14647]
 [25495 25322 17507 29760 24825]
 [17500 28937 15467 20072 14323]
 [25487 28394 19014 28211 19132]
 [21267 27073 25370 16419 25723]
 [23148 15051 14881 26747 17797]
 [28200 28240 10946 20652 19019]
 [14077 22684 26369